#   EXP Cube Config

#   Debug ( full / Default:normal / none )
Debug: normal

#   Cube Recipe Switch
#   レシピを有効にするかどうか
CubeRecipe: false

#   Cube ExpOrb Mode
#   true:Orb , false:Direct
#   経験値の戻り方の指定、通常はDirectで指定
OrbMode: false

#   Cube Control Cool Time
#   CoolTick 1 = 0.05sec
#   CoolTick x CoolCount = 0.25sec( CoolTime )
#   アイテムクールタイムの設定、Tick割り込み頻度、回数で、トータルのクールタイムを決定する
#   上手く処理ができない場合は、クールタイムを設けると上手く行く時もあります
CoolTick: 1
CoolCount: 1

#   Action Messages
messages:
  EC_ERROR: "%$4コンフィグの指定に誤りがあります"
  InvFull: "%$a[ExpCube] %$4インベントリに空きがありません"
  ExpToCube: "%$a[ExpCube] %$b経験値を100キューブに入れました %$f( %minExp%/%maxExp% )"
  ExpFromCube: "%$a[ExpCube] %$bキューブから100経験値を取り出しました %$f( %minExp%/%maxExp% )"
  NoEnough: "%$a[ExpCube] %$4経験値が足りません %$f( %TotalExp% EXP )"
  CubeFull: "%$a[ExpCube] %$4このキューブは一杯です"
  CubeEmpty: "%$a[ExpCube] %$4このキューブは空です"
  Sneaking: "%$a[ExpCube] %$eスニークしながら使って下さい"
  NoPermission: "%$4貴方には権限がありません"
  ZeroCube1: "%$eスニーク%$fしながら"
  ZeroCube2: "%$b右クリック%$fで貯める"
  ZeroCube3: "%$b左クリック%$fで取り出す"
  insideErr: "%$4このコマンドはゲーム内から実行してください"
#  EC_ERROR: "%$4ExpCube Config Error"
#  InvFull: "%$a[ExpCube] %$4There is no space in the inventory"
#  ExpToCube: "%$a[ExpCube] %$bExp to Cube at 100.(%minExp%/%maxExp%)"
#  ExpFromCube: "%$a[ExpCube] %$bEXP from Cube at 100.(%minExp%/%maxExp%)"
#  NoEnough: "%$a[ExpCube] %$4Not enough EXP, You have %TotalExp% EXP"
#  CubeFull: "%$a[ExpCube] %$4Full EXP this Cube."
#  CubeEmpty: "%$a[ExpCube] %$4Empty this Cube."
#  Sneaking: "%$a[ExpCube] %$eExpCube use to Sneak"
#  NoPermission: "%$4You do not have permission."
#  ZeroCube1: "%$fWhile %$esneaking"
#  ZeroCube2: "%$bRight click%$f to save"
#  ZeroCube3: "%$fRemove by %$bleft click"
#  insideErr: "%$4Please execute this command from inside the game."
  