#EXP Cube Config

#Debug ( full / Default:normal / none )
Debug: normal

#Cube Recipe Switch
CubeRecipe: false

#Cube ExpOrb Mode
# true:Orb , false:Direct
OrbMode: false

#Action Messages
messages:
  ExpToCube: "§b[ExpCube] Exp to Cube at 100."
  ExpFromCube: "§b[ExpCube] EXP from Cube at 100."
  NoEnough: "§4[ExpCube] Not enough EXP."
  CubeFull: "§4[ExpCube] Full EXP this Cube."
  CubeEmpty: "§4[ExpCube] Empty this Cube."
  Sneaking: "§e[ExpCube] ExpCube use to Sneak"
  NoPermission: "§4貴方は権限を持っていません"
  