#EXP Cube Config

#Debug ( full / Default:normal / none )
Debug: normal

#Cube Recipe Switch
#レシピを有効にするかどうか
CubeRecipe: false

#Cube ExpOrb Mode
# true:Orb , false:Direct
#経験値の戻り方の指定、通常はDirectで指定
OrbMode: false

#Action Messages
#各種メッセージ類
messages:
  EC_ERROR: "$4コンフィグの指定に誤りがあります"
  ExpToCube: "§a[ExpCube] §b経験値を100キューブに入れました ( %minExp%/%maxExp% )"
  ExpFromCube: "§a[ExpCube] §bキューブから100経験値を取り出しました ( %minExp%/%maxExp% )"
  NoEnough: "§a[ExpCube] §4経験値が足りません ( %TotalExp% EXP )"
  CubeFull: "§a[ExpCube] §4このキューブは一杯です"
  CubeEmpty: "§a[ExpCube] §4このキューブは空です"
  Sneaking: "§a[ExpCube] §eスニークしながら使って下さい"
  NoPermission: "§4貴方には権限がありません"
  ZeroCube1: "§eスニーク§fしながら"
  ZeroCube2: "§b右クリック§fで貯める"
  ZeroCube3: "§b左クリック§fで取り出す"
  insideErr: "$4このコマンドはゲーム内から実行してください"
 