main: com.mycompany.expcube.ExpCube
name: ExpCube
version: 0.3.6
description: Exp Cube plugin
author: Kumaisu
database: true
api-version: 1.14
commands:
    ExpCube:
        description: ExpCube Control Command
permissions:
    ExpCube.admin:
        description: ExpCube Admin Command
    ExpCube.cubeget:
        description: give ExpCube Command
    ExpCube.console:
        description: Remote Console Command
    ExpCube.set:
        description: Exp to Cube Motion Flag
    ExpCube.get:
        description: Exp from Cube Motion Flag
