name: ExpCube
version: 0.4.0
main: io.github.kumaisu.expcube.ExpCube
api-version: '1.21'
description: Exp Cube plugin
author: Kumaisu
database: true
commands:
    ExpCube:
        description: ExpCube Control Command
permissions:
    ExpCube.admin:
        description: ExpCube Admin Command
    ExpCube.cubeget:
        description: give ExpCube Command
    ExpCube.console:
        description: Remote Console Command
    ExpCube.set:
        description: Exp to Cube Motion Flag
    ExpCube.get:
        description: Exp from Cube Motion Flag
