main: com.mycompany.expcube.ExpCube
name: ExpCube
version: 0.3
description: Exp Cube plugin
author: Kumaisu
database: true
commands:
    cubeget:
        description: Give ExpCube Item
        aliases: cg
        permission: ExpCube.cubeget
        permission-message: You do not have permission.
        usage: /<command>
    ExpCube:
        description: Admin Command
        permission: ExpCube.admin
        permission-message: You do not have permission.
        usage: |
            /<command> reload
            /<command> status
            /<command> mode
            /<command> playerstatus/ps
            /<command> console [full/normal/none]
permissions:
    ExpCube.set:
        description: Exp to Cube Motion Flag
        default: op
    ExpCube.get:
        description: Exp from Cube Motion Flag
        default: op
